"""create galaxy resource missions

Revision ID: 1148ac771bd8
Revises: 454104462a6a
Create Date: 2026-10-02 14:16:34.975207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1148ac771bd8'
down_revision: Union[str, Sequence[str], None] = '454104462a6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galaxy_resource_missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('target_galaxy', sa.Integer(), nullable=False),
    sa.Column('target_system', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finishes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_galaxy_resource_mission_one_active_per_planet', 'galaxy_resource_missions', ['planet_id'], unique=True, postgresql_where=sa.text("status = 'active'"), sqlite_where=sa.text("status = 'active'"))
    op.create_index(op.f('ix_galaxy_resource_missions_planet_id'), 'galaxy_resource_missions', ['planet_id'], unique=False)
    op.create_index(op.f('ix_galaxy_resource_missions_status'), 'galaxy_resource_missions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_galaxy_resource_missions_status'), table_name='galaxy_resource_missions')
    op.drop_index(op.f('ix_galaxy_resource_missions_planet_id'), table_name='galaxy_resource_missions')
    op.drop_index('ix_galaxy_resource_mission_one_active_per_planet', table_name='galaxy_resource_missions', postgresql_where=sa.text("status = 'active'"), sqlite_where=sa.text("status = 'active'"))
    op.drop_table('galaxy_resource_missions')
    # ### end Alembic commands ###
