"""create galaxy scout missions

Revision ID: 34957f7b7914
Revises: 7734ccffaea5
Create Date: 2026-10-02 09:30:43.303575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34957f7b7914'
down_revision: Union[str, Sequence[str], None] = '7734ccffaea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galaxy_scout_missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('target_galaxy', sa.Integer(), nullable=False),
    sa.Column('target_system', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finishes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_galaxy_scout_missions_planet_id'), 'galaxy_scout_missions', ['planet_id'], unique=False)
    op.create_index(op.f('ix_galaxy_scout_missions_status'), 'galaxy_scout_missions', ['status'], unique=False)
    op.drop_index(op.f('ix_expedition_one_active_per_planet'), table_name='expedition_items', postgresql_where="((status)::text = 'active'::text)")
    op.create_index(
    "ix_galaxy_scout_one_active_per_planet",
    "galaxy_scout_missions",
    ["planet_id"],
    unique=True,
    postgresql_where=sa.text("status = 'active'"),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_expedition_one_active_per_planet'), 'expedition_items', ['planet_id'], unique=True, postgresql_where="((status)::text = 'active'::text)")
    op.drop_index(op.f('ix_galaxy_scout_missions_status'), table_name='galaxy_scout_missions')
    op.drop_index(op.f('ix_galaxy_scout_missions_planet_id'), table_name='galaxy_scout_missions')
    op.drop_index(
    "ix_galaxy_scout_one_active_per_planet",
    table_name="galaxy_scout_missions",
)
    op.drop_table('galaxy_scout_missions')
    # ### end Alembic commands ###
