"""create galaxy known systems

Revision ID: 454104462a6a
Revises: 34957f7b7914
Create Date: 2026-10-02 09:43:20.973248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '454104462a6a'
down_revision: Union[str, Sequence[str], None] = '34957f7b7914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galaxy_known_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('target_galaxy', sa.Integer(), nullable=False),
    sa.Column('target_system', sa.Integer(), nullable=False),
    sa.Column('report_payload', sa.JSON(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planet_id', 'target_galaxy', 'target_system', name='uq_galaxy_known_system_planet_target')
    )
    op.create_index(op.f('ix_galaxy_known_systems_planet_id'), 'galaxy_known_systems', ['planet_id'], unique=False)
    op.create_index(op.f('ix_galaxy_known_systems_target_galaxy'), 'galaxy_known_systems', ['target_galaxy'], unique=False)
    op.create_index(op.f('ix_galaxy_known_systems_target_system'), 'galaxy_known_systems', ['target_system'], unique=False)
    op.drop_index(op.f('ix_galaxy_scout_one_active_per_planet'), table_name='galaxy_scout_missions', postgresql_where="((status)::text = 'active'::text)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_galaxy_scout_one_active_per_planet'), 'galaxy_scout_missions', ['planet_id'], unique=True, postgresql_where="((status)::text = 'active'::text)")
    op.drop_index(op.f('ix_galaxy_known_systems_target_system'), table_name='galaxy_known_systems')
    op.drop_index(op.f('ix_galaxy_known_systems_target_galaxy'), table_name='galaxy_known_systems')
    op.drop_index(op.f('ix_galaxy_known_systems_planet_id'), table_name='galaxy_known_systems')
    op.drop_table('galaxy_known_systems')
    # ### end Alembic commands ###
