"""create ships

Revision ID: 4963a551ccb1
Revises: 4e079ffdb015
Create Date: 2026-10-01 15:45:11.186978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4963a551ccb1'
down_revision: Union[str, Sequence[str], None] = '4e079ffdb015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ship_queue_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('ship_code', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finishes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ship_queue_items_planet_id'), 'ship_queue_items', ['planet_id'], unique=False)
    op.create_table('ship_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('ship_code', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planet_id', 'ship_code', name='uq_planet_ship')
    )
    op.create_index(op.f('ix_ship_states_planet_id'), 'ship_states', ['planet_id'], unique=False)
    op.drop_index(op.f('ix_research_queue_one_active_per_planet'), table_name='research_queue_items', postgresql_where="((status)::text = 'active'::text)")
    op.create_index(
    "ix_ship_queue_one_active_per_planet",
    "ship_queue_items",
    ["planet_id"],
    unique=True,
    postgresql_where=sa.text("status = 'active'"),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_research_queue_one_active_per_planet'), 'research_queue_items', ['planet_id'], unique=True, postgresql_where="((status)::text = 'active'::text)")
    op.drop_index(op.f('ix_ship_states_planet_id'), table_name='ship_states')
    op.drop_table('ship_states')
    op.drop_index(op.f('ix_ship_queue_items_planet_id'), table_name='ship_queue_items')
    op.drop_index(
    "ix_ship_queue_one_active_per_planet",
    table_name="ship_queue_items",
)
    op.drop_table('ship_queue_items')
    # ### end Alembic commands ###
