"""create research

Revision ID: 4e079ffdb015
Revises: 4b1e6f2c9a10
Create Date: 2026-10-01 14:53:41.908904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e079ffdb015'
down_revision: Union[str, Sequence[str], None] = '4b1e6f2c9a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_queue_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('research_code', sa.String(length=32), nullable=False),
    sa.Column('target_level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finishes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_queue_items_planet_id'), 'research_queue_items', ['planet_id'], unique=False)
    op.create_table('research_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('research_code', sa.String(length=32), nullable=False),
    sa.Column('level', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planet_id', 'research_code', name='uq_planet_research')
    )
    op.create_index(op.f('ix_research_states_planet_id'), 'research_states', ['planet_id'], unique=False)
    op.drop_index(op.f('ix_building_queue_one_active_per_planet'), table_name='building_queue_items', postgresql_where="((status)::text = 'active'::text)")
    op.create_index(
    "ix_research_queue_one_active_per_planet",
    "research_queue_items",
    ["planet_id"],
    unique=True,
    postgresql_where=sa.text("status = 'active'"),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_building_queue_one_active_per_planet'), 'building_queue_items', ['planet_id'], unique=True, postgresql_where="((status)::text = 'active'::text)")
    op.drop_index(op.f('ix_research_states_planet_id'), table_name='research_states')
    op.drop_table('research_states')
    op.drop_index(op.f('ix_research_queue_items_planet_id'), table_name='research_queue_items')
    op.drop_index(
    "ix_research_queue_one_active_per_planet",
    table_name="research_queue_items",
)
    op.drop_table('research_queue_items')
    # ### end Alembic commands ###
